from fastapi import FastAPI

from pydantic import BaseModel

app= FastAPI()

class peliculas (BaseModel):
    id:int
    marca:str
    genero:str
    año:int

peliculas_list= [peliculas(id=1, marca="universal", genero= "comedia", año= "2018"),
                 peliculas(id=2, marca="paramount", genero= "drama", año= "2019"),
                 peliculas(id=3, marca="warner bros", genero= "aventura", año= "2017"), 
                 peliculas(id=4, marca="20th century fox", genero= "fantasía", año= "2016"),
                 peliculas(id=5, marca="lionsgate", genero= "animación", año= "2014"),
                 peliculas(id=6, marca="disney", genero= "musical", año= "2021"), 
                 peliculas(id=7, marca="dreamworks", genero= "romance", año= "2018"),
                 peliculas(id=8, marca="columbia pictures", genero= "suspense", año= "2017"), 
                 peliculas(id=9, marca="universal", genero="acción", año= "2019"), 
                 peliculas(id=10, marca="sony", genero= "ciencia ficción", año= "2016"), 
                 peliculas(id=11, marca= "warner bros", genero= "comedia", año= "2015"), 
                 peliculas(id=12, marca= "paramount", genero= "drama", año= "2018"), 
                 peliculas(id=13, marca= "disney", genero= "aventura", año= "2020"), 
                 peliculas(id=14,marca= "20th century fox", genero= "fantasía", año= "2019"), 
                 peliculas(id=15,marca= "lionsgate", genero= "animación", año= "2017"), 
                 peliculas(id=16,marca= "dreamworks", genero= "musical", año= "2015"), 
                 peliculas(id=17,marca= "columbia pictures", genero="romance", año= "2014"),
                 peliculas(id=18,marca= "universal", genero= "suspense", año= "2016"),
                 peliculas(id=19,marca= "sony", genero= "acción", año= "2021"), 
                 peliculas(id=20,marca= "warner bros", genero= "ciencia ficción", año= "2017"), 
                 peliculas(id=21,marca= "paramount", genero="comedia", año= "2016"), 
                 peliculas(id=22,marca= "disney", genero= "drama", año= "2015"), 
                 peliculas(id=23,marca= "20th century fox", genero= "aventura", año= "2020"),
                 peliculas(id=24,marca= "lionsgate", genero= "fantasía", año= "2019"), 
                 peliculas(id=25,marca="dreamworks", genero= "animación", año= "2018"), 
                 peliculas(id=26,marca= "columbia pictures", genero= "musical", año= "2017"),
                 peliculas(id=27,marca= "universal", genero= "romance", año= "2016"),
                 peliculas(id=28,marca= "sony", genero="suspense", año= "2015"),
                 peliculas(id=29,marca= "warner bros", genero= "acción", año="2018"), 
                 peliculas(id=30,marca= "paramount", genero= "ciencia ficción", año= "2019"),
                 peliculas(id=31,marca= "disney", genero= "comedia", año= "2017"),
                 peliculas(id=32,marca= "20th century fox", genero= "drama", año= "2016"),
                 peliculas(id=33,marca= "lionsgate", genero= "aventura", año= "2015"), 
                 peliculas(id=34,marca= "dreamworks", genero= "fantasía", año= "2014"), 
                 peliculas(id=35,marca="columbia pictures", genero= "animación", año= "2020"),
                 peliculas(id=36,marca= "universal", genero= "musical", año= "2016"), 
                 peliculas(id=37,marca= "sony", genero= "romance", año= "2017"),
                 peliculas(id=38,marca= "warner bros", genero= "suspense", año= "2016"),
                 peliculas(id=39,marca= "paramount", genero="acción", año= "2015"), 
                 peliculas(id=40,marca= "disney", genero= "ciencia ficción", año="2020"),
                 peliculas(id=41,marca= "20th century fox", genero= "comedia", año= "2018"),
                 peliculas(id=42,marca= "lionsgate", genero="drama", año= "2017"), 
                 peliculas(id=43,marca= "dreamworks", genero= "aventura", año="2015"),
                 peliculas(id=44,marca= "columbia pictures", genero= "fantasía", año= "2019"),
                 peliculas(id=45,marca= "universal", genero= "animación", año= "2016"),
                 peliculas(id=46,marca= "sony", genero= "musical", año= "2014"),
                 peliculas(id=47,marca= "warner bros", genero= "romance", año= "2021"),
                 peliculas(id=48,marca= "paramount", genero= "suspense", año= "2020"),
                 peliculas(id=49,marca= "disney", genero= "acción", año= "2019"),
                 peliculas(id=50,marca= "20th century fox", genero= "ciencia ficción", año= "2017"),
                 peliculas(id=51,marca= "lionsgate", genero= "comedia", año= "2016"), 
                 peliculas(id=52,marca= "dreamworks", genero= "drama", año= "2015"),
                 peliculas(id=53,marca= "columbia pictures", genero= "aventura", año= "2020"),
                 peliculas(id=54,marca= "universal", genero= "fantasía", año= "2019"), 
                 peliculas(id=55,marca= "sony", genero= "animación", año= "2018"),
                 peliculas(id=56,marca= "warner bros", genero= "musical", año= "2017"),
                 peliculas(id=57,marca= "paramount", genero= "romance", año= "2016"),
                 peliculas(id=58,marca= "disney", genero= "Animacion", año= "2015"),
                 peliculas(id=59,marca= "20th century fox", genero= "drama", año= "2018"),
                 peliculas(id=60,marca= "lionsgate", genero= "ciencia ficción", año="2019"),
                 peliculas(id=61,marca= "dreamworks", genero= "comedia", año= "2017"),
                 peliculas(id=62,marca="columbia pictures", genero= "drama", año= "2016"),
                 peliculas(id=63,marca= "universal", genero= "aventura", año= "2015"),
                 peliculas(id=64,marca= "sony",genero= "fantasía", año= "2020"),
                 peliculas(id=65,marca= "warner bros", genero= "animación", año= "2019"),
                 peliculas(id=66,marca= "paramount", genero= "musical", año= "2017"),
                 peliculas(id=67,marca= "disney", genero= "romance", año= "2018"),
                 peliculas(id=68,marca= "20th century fox", genero= "suspense", año= "2015"),
                 peliculas(id=69,marca= "lionsgate", genero= "acción", año= "2020"),
                 peliculas(id=70,marca= "dreamworks", genero= "ciencia ficción", año= "2018"),
                 peliculas(id=71,marca= "columbia pictures", genero= "comedia", año= "2012"),
                 peliculas(id=72,marca= "universal", genero= "drama", año= "2016"),
                 peliculas(id=73,marca= "sony", genero= "aventura", año="2015"),
                 peliculas(id=74,marca= "warner bros", genero= "fantasía", año= "2020"),
                 peliculas(id=75,marca= "paramount", genero= "animación", año= "2019"),
                 peliculas(id=76,marca= "disney", genero= "musical", año= "2018"),
                 peliculas(id=77,marca= "20th century fox", genero= "romance", año= "2017"),
                 peliculas(id=78,marca= "lionsgate", genero= "suspense", año= "2016"),
                 peliculas(id=79,marca= "dreamworks", genero="acción", año= "2011"),
                 peliculas(id=80,marca= "columbia pictures", genero= "ciencia ficción", año= "2020"),
                 peliculas(id=81,marca= "universal", genero= "comedia", año= "2019"),
                 peliculas(id=82,marca= "sony", genero= "drama", año= "2018"),
                 peliculas(id=83,marca= "warner bros", genero= "aventura", año="2017"),
                 peliculas(id=84,marca= "paramount", genero= "fantasía", año= "2016"),
                 peliculas(id=85,marca= "disney", genero= "animación", año= "2015"),
                 peliculas(id=86,marca= "20th century fox", genero= "musical", año= "2020"),
                 peliculas(id=87,marca= "lionsgate", genero= "romance", año= "2019"),
                 peliculas(id=88,marca= "dreamworks", genero= "suspense", año= "2013"),
                 peliculas(id=89,marca= "columbia pictures",genero= "acción", año= "2007"),
                 peliculas(id=90,marca= "universal", genero= "ciencia ficción", año= "2016"),
                 peliculas(id=91,marca= "sony", genero= "comedia", año= "2015"),
                 peliculas(id=92,marca= "warner bros", genero= "drama", año= "2020"),
                 peliculas(id=93,marca= "paramount", genero= "aventura", año= "2014"),
                 peliculas(id=94,marca= "disney", genero= "fantasía", año="2018"),
                 peliculas(id=95,marca= "20th century fox", genero= "animación", año= "2017"),
                 peliculas(id=96,marca= "lionsgate", genero= "musical", año= "2016"),
                 peliculas(id=97,marca= "dreamworks", genero= "romance", año= "2015"),
                 peliculas(id=98,marca= "columbia pictures", genero= "suspense", año= "2020"),
                 peliculas(id=99,marca= "universal", genero= "acción", año= "2019"),
                 peliculas(id=100,marca= "sony", genero= "ciencia ficción", año= "2018"),
                 peliculas(id=101,marca= "warner bros", genero= "comedia", año= "2017"),
                 peliculas(id=102,marca= "paramount", genero= "drama", año= "2016"),
                 peliculas(id=103,marca="disney", genero= "aventura", año= "2015"),
                 peliculas(id=104,marca= "20th century fox", genero= "fantasía", año= "2010"),
                 peliculas(id=105,marca= "lionsgate", genero= "animación", año= "2019"),
                 peliculas(id=106,marca= "dreamworks", genero= "musical", año= "2018"),
                 peliculas(id=107,marca= "columbia pictures", genero= "romance", año= "2017"),
                 peliculas(id=109,marca= "sony", genero= "acción", año= "2015"),
                 peliculas(id=110,marca= "warner bros", genero= "ciencia ficción", año= "2020"),
                 peliculas(id=111,marca= "paramount", genero= "comedia", año= "2019"),
                 peliculas(id=112,marca= "disney", genero= "drama", año= "2010"),
                 peliculas(id=113,marca= "20th century fox", genero= "aventura", año= "2017"),
                 peliculas(id=114,marca= "lionsgate", genero= "fantasía", año= "2016"),
                 peliculas(id=115,marca= "dreamworks", genero= "animación", año= "2013"),
                 peliculas(id=116,marca= "columbia pictures", genero= "musical", año= "2005"),
                 peliculas(id=117,marca= "universal", genero= "romance", año= "2019"),
                 peliculas(id=118,marca= "sony", genero= "suspense", año= "2018"),
                 peliculas(id=119,marca= "warner bros", genero="acción", año="2017"),
                 peliculas(id=120,marca= "paramount", genero= "ciencia ficción", año= "2016"),
                 peliculas(id=121,marca= "disney", genero= "comedia", año= "2012"),
                 peliculas(id=122,marca= "20th century fox", genero= "drama", año= "2020"),
                 peliculas(id=123,marca= "lionsgate", genero= "Animacion", año= "2008"),
                 peliculas(id=124,marca= "dreamworks", genero= "fantasía", año= "2013"), 
                 peliculas(id=125,marca= "columbia pictures", genero= "animación", año= "2017"),
                 peliculas(id=126,marca= "universal", genero= "musical", año= "2015"),
                 peliculas(id=127,marca= "sony", genero= "romance", año= "2015"),
                 peliculas(id=128,marca= "warner bros", genero= "suspense", año= "2020"),
                 peliculas(id=129,marca= "paramount", genero= "acción", año= "2019"),
                 peliculas(id=130,marca= "disney", genero= "ciencia ficción", año= "2018"),
                 peliculas(id=131,marca= "20th century fox", genero="comedia", año= "2017"),
                 peliculas(id=132,marca= "lionsgate", genero= "drama", año= "2016"),
                 peliculas(id=133,marca= "dreamworks", genero= "aventura", año= "2017"),
                 peliculas(id=135,marca= "columbia pictures", genero= "fantasía", año= "2020"),
                 peliculas(id=136,marca= "universal", genero= "animación", año= "2019"),
                 peliculas(id=137,marca= "sony", genero= "musical", año= "2009"),
                 peliculas(id=138,marca= "warner bros", genero= "romance", año= "2017"),
                 peliculas(id=139,marca= "paramount", genero= "suspense", año= "2016"),
                 peliculas(id=140,marca= "disney", genero= "acción", año= "2015"),
                 peliculas(id=141,marca= "20th century fox", genero= "ciencia ficción", año= "2020"),
                 peliculas(id=142,marca= "lionsgate", genero= "comedia", año= "2019"),
                 peliculas(id=143,marca= "dreamworks", genero= "drama", año= "2018"),
                 peliculas(id=144,marca= "columbia pictures", genero= "aventura", año= "2014"),
                 peliculas(id=145,marca= "universal", genero= "fantasía", año= "2016"),
                 peliculas(id=146,marca= "sony", genero= "animación", año= "2015"),
                 peliculas(id=147,marca= "warner bros", genero= "musical", año= "2020"),
                 peliculas(id=148,marca= "paramount", genero= "romance", año= "2017"),
                 peliculas(id=149,marca= "disney", genero= "suspense", año= "2018"),
                 peliculas(id=150,marca= "20th century fox", genero= "acción", año= "2017"),
                 peliculas(id=151,marca= "lionsgate", genero= "ciencia ficción", año= "2016"),
                 peliculas(id=152,marca= "dreamworks", genero= "comedia", año= "2012"),
                 peliculas(id=153,marca= "columbia pictures", genero= "drama", año= "2020"),
                 peliculas(id=154,marca= "universal", genero= "aventura", año= "2020"),
                 peliculas(id=155,marca= "sony", genero= "fantasía", año= "2018"),
                 peliculas(id=156,marca= "warner bros", genero= "animación", año= "2019"),
                 peliculas(id=157,marca= "paramount", genero= "musical", año= "2016"),
                 peliculas(id=158,marca= "disney", genero= "romance", año= "2015"),
                 peliculas(id=159,marca= "20th century fox", genero= "suspense", año= "2006"),
                 peliculas(id=160,marca= "lionsgate", genero="acción", año= "2019"),
                 peliculas(id=161,marca= "dreamworks", genero="ciencia ficción", año="2015"),
                 peliculas(id=162,marca= "columbia pictures", genero= "comedia", año= "2019"),
                 peliculas(id=163,marca= "universal", genero= "drama", año= "2016"),
                 peliculas(id=164,marca= "sony", genero= "aventura", año= "2015"),
                 peliculas(id=165,marca= "warner bros", genero= "fantasía", año= "2013"),
                 peliculas(id=166,marca= "paramount", genero= "animación", año= "2011"),
                 peliculas(id=167,marca= "disney", genero= "musical", año= "2007"),
                 peliculas(id=168,marca= "20th century fox", genero= "romance", año= "2006"),
                 peliculas(id=169,marca= "lionsgate", genero= "suspense", año= "2010"),
                 peliculas(id=170,marca= "dreamworks", genero= "acción", año= "2016"),
                 peliculas(id=171,marca= "columbia pictures", genero= "ciencia ficción", año= "2017"),
                 peliculas(id=172,marca= "universal", genero= "comedia", año= "2012"),
                 peliculas(id=173,marca= "sony", genero= "drama", año= "2018"),
                 peliculas(id=174,marca= "warner bros", genero= "aventura", año= "2019"),
                 peliculas(id=175,marca= "paramount", genero= "fantasía", año= "2016"),
                 peliculas(id=176,marca= "disney", genero= "animación", año= "2019"),
                 peliculas(id=177,marca= "universal", genero= "acción", año= "2015"),
                 peliculas(id=178,marca= "paramount", genero= "ciencia ficción", año= "2018"),
                 peliculas(id=179,marca= "warner bros", genero= "comedia", año= "2011"),
                 peliculas(id=180,marca= "disney", genero= "drama", año= "2019"),
                 peliculas(id=181,marca= "20th century fox", genero= "aventura", año= "2013"),
                 peliculas(id=182,marca= "sony", genero= "fantasía", año= "2020"),
                 peliculas(id=183,marca= "lionsgate", genero= "animación", año= "2010"),
                 peliculas(id=184,marca= "dreamworks", genero= "musical", año= "2005"),
                 peliculas(id=185,marca= "columbia pictures", genero= "romance", año= "2011"),
                 peliculas(id=186,marca= "universal", genero= "suspense", año= "2009"),
                 peliculas(id=187,marca= "paramount", genero= "acción", año= "2012"),
                 peliculas(id=188,marca= "warner bros", genero= "ciencia ficción", año= "2014"),
                 peliculas(id=189,marca= "disney", genero= "comedia", año= "2017"),
                 peliculas(id=190,marca= "20th century fox", genero= "drama", año= "2012"),
                 peliculas(id=191,marca= "sony", genero= "aventura", año= "2020"),
                 peliculas(id=192,marca= "lionsgate", genero= "fantasía", año= "2010"),
                 peliculas(id=193,marca= "dreamworks", genero= "animación", año= "2007"),
                 peliculas(id=194,marca= "columbia pictures", genero= "musical", año= "2012"),
                 peliculas(id=195,marca= "universal", genero= "romance", año= "2013"),
                 peliculas(id=196,marca= "paramount", genero= "suspense", año= "2018"),
                 peliculas(id=197,marca= "warner bros", genero= "acción", año= "2010"),
                 peliculas(id=198,marca= "disney", genero= "ciencia ficción", año= "2014"),
                 peliculas(id=199,marca= "20th century fox", genero= "comedia", año= "2015"),
                 peliculas(id=200,marca= "sony", genero= "drama", año= "2021")]


@app.get("/peliculasclass/")
async def imprimir():
    return (peliculas_list)
#http://127.0.0.1:8000/peliculasclass/

@app.get("/peliculasclass/{id}")
async def peliculasclass(id:int):
    peliculas=filter (lambda peliculas: peliculas.id == id, peliculas_list)  #Función de orden superior
    try:
        return list(peliculas)[0]
    except:
        return{"error":"No se ha encontrado la pelicula"}
    #http://127.0.0.1:8000/peliculasclass/1